//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSmartClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dosen_tbl
    {
        public string nid { get; set; }
        public string nama_dosen { get; set; }
        public string email_dosen { get; set; }
    }
}
