//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSmartClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jadwal_tbl
    {
        public string id_jadwal { get; set; }
        public string id_ruang { get; set; }
        public string id_kelas { get; set; }
        public string nid { get; set; }
        public string id_matkul { get; set; }
        public string tanggal_jadwal { get; set; }
        public string start_kuliah { get; set; }
        public string finish_kuliah { get; set; }
    }
}
