//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSmartClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_tbl
    {
        public string absen_log { get; set; }
        public string nim { get; set; }
        public string id_kelas { get; set; }
        public string id_matkul { get; set; }
        public string nid { get; set; }
        public string url_foto { get; set; }
        public string tanggal_absen { get; set; }
        public string start_time { get; set; }
        public string last_time { get; set; }
    }
}
