//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSmartClass.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mahasiswa_tbl
    {
        public string id { get; set; }
        public string NIM { get; set; }
        public string Nama { get; set; }
        public string Email { get; set; }
    }
}
