//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSmartClass.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smartclassdbContext : DbContext
    {
        public smartclassdbContext()
            : base("name=smartclassdbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<absen_tbl> absen_tbl { get; set; }
        public DbSet<dosen_tbl> dosen_tbl { get; set; }
        public DbSet<jadwal_tbl> jadwal_tbl { get; set; }
        public DbSet<kelas_tbl> kelas_tbl { get; set; }
        public DbSet<log_tbl> log_tbl { get; set; }
        public DbSet<mahasiswa_tbl> mahasiswa_tbl { get; set; }
        public DbSet<matkul_tbl> matkul_tbl { get; set; }
        public DbSet<ruangkuliah_tbl> ruangkuliah_tbl { get; set; }
    }
}
